cmake_minimum_required(VERSION 3.10)
project(HealthCompass)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(SFML 2.5 COMPONENTS graphics window system REQUIRED)

add_executable(HealthCompass
    main.cpp
    vptree.cpp
    features.cpp
)

target_link_libraries(HealthCompass sfml-graphics sfml-window sfml-system)
